---
title: "COVID19"
author: "dp"
date: "24 March 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RCurl)
library(jsonlite)
library(tidyverse)
library(gridExtra)

```

# CSSE


```{r}

covid_df<-jsonlite::fromJSON(RCurl::getURL("https://coronavirus-tracker-api.herokuapp.com/all"))

myexfn<-function(country_code){
  myn<-which(covid_df$confirmed$locations$country_code==country_code)
  crapdates<-names(covid_df$confirmed$locations$history[myn[1],]) %>% as.Date(format="%m/%d/%y")
  cvalues<-as.numeric(base::colSums(covid_df$confirmed$locations$history[myn,]))
  retdat<-data.frame(Date=crapdates,Cvalues=cvalues) %>% 
    dplyr::arrange(Date)
  colnames(retdat)<-c("Date",country_code)
  return(retdat)
}

```

## Country Comparison

```{r}

purrr::map(.x=list("CH","IT","DE","FR","GB","ES"),.f=myexfn) %>%
  purrr::reduce(.f=dplyr::full_join,by="Date") %>%
  tidyr::gather(Country,Value,-Date) %>% 
  ggplot(aes(x=Date,y=Value,colour=Country)) +
  geom_point() +
  geom_line() + 
  scale_y_log10() +
  labs(x=NULL,y="Confirmed cases (log scale)",
       title="COVID-19 confirmed cases (CSSE John Hopkins)") +
  theme(legend.position="bottom")

```

```{r}
purrr::map(.x=list("CH","IT","DE","FR","GB","ES","US"),.f=myexfn) %>%
  reduce(.f=dplyr::full_join,by="Date") %>% 
  dplyr::select(-Date) %>%
  dplyr::mutate_all(~c(NA,diff(log(.)))) %>%
  tail(10)
```

## CH
```{r}
  mydf<-myexfn("CH") %>% 
    dplyr::filter(CH > 100) %>%
    dplyr::mutate(
      Label=format(Date,"%m-%d"),
      t=1:n(),
      dCH=CH-dplyr::lag(CH,1),
      gr=dCH/CH,
      egr=c(NA,base::diff(log(CH)))
    )
```

```{r}
summary(myfit<-lm(log(CH)~t,data=mydf))
mydf$fit<-exp(myfit$fitted.values)
mydf$dfit<-c(NA,diff(mydf$fit))
mydf
```

```{r}
mydbl<-log(2)/myfit$coefficients[2]
P1<-mydf %>%
  ggplot() +
  geom_point(aes(x=t,y=CH),color="#F8766D") + 
  geom_point(aes(x=t,y=fit),color="#00BFC4") +
  geom_line(aes(x=t,y=fit),color="#00BFC4") +
  scale_y_log10() +
  annotate("text", x=5, y=5000, label=sprintf("Doubling time: %.2f days",mydbl))

P2 <- mydf %>% 
  dplyr::select(Label,dCH,dfit) %>% 
  tidyr::gather(Variable,Value,-Label) %>%
  ggplot(aes(x=Label,y=Value,fill=Variable)) +
  geom_bar(stat="identity",position=position_dodge()) +
  theme(legend.position="bottom",axis.text.x = element_text(angle = 90))

grid.arrange(P1,P2)
```

# Corona-data.ch

```{r}
jnk<-read_csv("https://raw.githubusercontent.com/daenuprobst/covid19-cases-switzerland/master/covid19_cases_switzerland.csv")

mydf<-jnk %>%
  dplyr::select(Date,CH) %>%
  dplyr::mutate(
    Label=format(Date,"%m-%d"),
    t=1:n(),
    dCH=CH-dplyr::lag(CH,1),
    gr=dCH/CH,
    egr=c(NA,base::diff(log(CH)))
  )

summary(myfit<-lm(log(CH)~t,data=mydf))

mydf$fit<-exp(myfit$fitted.values)
mydf$dfit<-c(NA,diff(mydf$fit))
mydf
```

```{r}
mydbl<-log(2)/myfit$coefficients[2]

P1<-mydf %>%
  ggplot() +
  geom_point(aes(x=t,y=CH),color="#F8766D") + 
  geom_point(aes(x=t,y=fit),color="#00BFC4") +
  geom_line(aes(x=t,y=fit),color="#00BFC4") +
  scale_y_log10() +
  annotate("text", x=5, y=5000, label=sprintf("Doubling time: %.2f days",mydbl))

P2 <- mydf %>% 
  dplyr::select(Label,dCH,dfit) %>% 
  tidyr::gather(Variable,Value,-Label) %>%
  ggplot(aes(x=Label,y=Value,fill=Variable)) +
  geom_bar(stat="identity",position=position_dodge()) +
  theme(legend.position="bottom",axis.text.x = element_text(angle = 90))

grid.arrange(P1,P2)
```

